kind: pipeline
name: default

steps:
  - name: test-ssh
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: dokku
    commands:
      - apk add --no-cache openssh-client
      - mkdir /root/.ssh
      - echo "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H grit-web02.grit.ucsb.edu >> /root/.ssh/known_hosts
      - ssh -o StrictHostKeyChecking=no dokku@grit-web02.grit.ucsb.edu "echo 'SSH connection successful!'"

