kind: pipeline
name: default

steps:
  - name: build
    image: jekyll/jekyll:latest
    commands:
      - bundle config set --local path vendor/bundle
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build
