kind: pipeline
name: default

steps:
  - name: build
    image: jekyll/jekyll:latest
    commands:
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build
    user:
      root
