kind: pipeline
type: docker
name: default

steps:
  - name: build-jekyll-site
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build

  - name: package
    image: plugins/docker
    settings:
      repo: localhost:5000/down2earthtest
      tags: latest
      dockerfile: Dockerfile
