kind: pipeline
type: docker
name: default

steps:
  - name: build-jekyll-site
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build

  - name: build-docker-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t down2earthtest .
      - docker save -o /tmp/down2earthtest.tar down2earthtest

  - name: deploy
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker load -i /tmp/down2earthtest.tar
      - dokku tags:deploy down2earthtest latest

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

