kind: pipeline
type: docker
name: default

steps:
  - name: build-jekyll-site
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build
  - name: prepare-git
    image: alpine/git
    commands:
      - git config --global user.email "youremail@example.com"
      - git config --global user.name "Your Name"
      - git init
      - git add .
      - git commit -m "Initial commit"

  - name: deploy-to-dokku
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: dokku
    commands:
      - apk add --no-cache openssh-client git
      - mkdir -p /root/.ssh
      - echo "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ssh-keyscan -H grit-web02.grit.ucsb.edu >> /root/.ssh/known_hosts
      - git remote add dokku dokku@grit-web02.grit.ucsb.edu:down2earthtest
      - git push dokku master

