kind: pipeline
type: docker
name: default

steps:
  - name: build-jekyll-site
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build

        #  - name: build-docker-image
        #    image: docker:dind
        #    volumes:
        #      - name: dockersock
        #        path: /var/run/docker.sock
        #    commands:
        #      - docker build -t down2earthtest .
        #      - docker save -o /tmp/down2earthtest.tar down2earthtest

        #  - name: deploy
        #    image: docker:dind
        #    environment:
        #      SSH_PRIVATE_KEY:
        #        from_secret: dokku
        #    volumes:
        #      - name: dockersock
        #        path: /var/run/docker.sock
        #    commands:
        #      - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
        #      - chmod 600 /root/.ssh/id_rsa
        #      - ssh-keyscan -H 128.111.100.48 >> /root/.ssh/known_hosts
        #      - docker load -i /tmp/down2earthtest.tar
        #      - scp /tmp/down2earthtest.tar dokku@128.111.100.48:/tmp/
        #      - ssh -o StrictHostKeyChecking=no dokku@128.111.100.48 "docker load -i /tmp/down2earthtest.tar"
        #      - ssh -o StrictHostKeyChecking=no dokku@128.111.100.48 "dokku tags:deploy down2earthtest latest"

        #volumes:
        #  - name: dockersock
        #    host:
        #      path: /var/run/docker.sock

