kind: pipeline
name: default

steps:
  - name: build
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src/Gemfile.lock
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build
