kind: pipeline
type: docker
name: default

steps:
  - name: build-jekyll-site
    image: jekyll/jekyll:latest
    commands:
      - chmod -R 777 /drone/src
      - bundle update --bundler
      - bundle install
      - bundle exec jekyll build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: grit-web02.grit.ucsb.edu
      username: dokku
      key:
        from_secret: dokku_ssh_key
      script:
        - git remote add dokku dokku@grit-web02.grit.ucsb.edu:down2earthtest
        - git push dokku master
